apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-server-auth-reader
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ include "metrics-server.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
