apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-server.fullname" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "metrics-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: https
  selector:
    {{- include "metrics-server.selectorLabels" . | nindent 4 }}
